language: python
python:  
  - "3.7"
env:
  - DJANGO=2.2

install:
  - pip install black
  - pip install importlib-metadata
  - pip install coverage
  - pip install django-crispy-forms==1.14.0
  - pip install flake8
  - pip install Django==2.2
  - pip install pytz==2022.4
  - pip install sqlparse==0.4.3
  - pip install coveralls
  - pip install newsapi-python
  
before_script:
- python BeHonest/manage.py migrate

before_script:
- python BeHonest/manage.py migrate

script:
  - black  ./
  - flake8 ./
  - cd BeHonest
  - coverage run --source=main,post manage.py test

after_success:
 coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $KP_ACCESSKEYIDDEV
  secret_access_key: $KP_SECRETACESSKEYDEV
  region: "us-west-2"  
  app: "BeHonest_Production"
  env: "BeHonestProd"
  bucket_name: "elasticbeanstalk-us-west-2-502730698175"
  on:
    branch: main


notifications:
  slack: gcivil-nyu:Hlh3yiC4qXUKTVMZDwsN6FJc